
# Include Haskell tools
language: haskell
ghc: 7.8

# Use the docker infrastructure
sudo: false

# Cache the installed Haskell stuff
cache:
  directories:
    - $HOME/.stack

notifications:
  email:
    on_success: change
    on_failure: change

addons:
  postgresql: "9.3"

env:
  global:
    - PKG_CONFIG_PATH=$HOME/.stack/local/lib/pkgconfig
    - LD_LIBRARY_PATH=$HOME/.stack/local/lib
    - LD_RUN_PATH=$HOME/.stack/local/lib
    - CFLAGS=-I$HOME/.stack/local/include
    - LDFLAGS=-L$HOME/.stack/local/lib
    - ZEROMQ=zeromq-4.1.2
    - LIBSODIUM=libsodium-1.0.3
  matrix:
    - STACK_YAML=stack.yaml

install:
  - travis_retry wget https://github.com/commercialhaskell/stack/releases/download/v0.1.2.0/stack-0.1.2.0-x86_64-linux.gz
  - gunzip stack-0.1.2.0-x86_64-linux.gz
  - mv stack-0.1.2.0-x86_64-linux stack
  - chmod +x stack
  - |
    # sudo apt-get remove libzmq1
    # Install libsodium
    if [ ! -f "$HOME/.stack/local/lib/pkgconfig/libsodium.pc" ]; then
      echo "libsodium not found; installing"
      wget https://download.libsodium.org/libsodium/releases/${LIBSODIUM}.tar.gz
      tar -xf ${LIBSODIUM}.tar.gz
      cd ${LIBSODIUM}
      ./configure --prefix=$HOME/.stack/local && make && make install
      cd ..
    else
      echo "libsodium found; skipping"
    fi
    # Install libzmq
    if [ ! -f "$HOME/.stack/local/lib/pkgconfig/libzmq.pc" ]; then
      echo "libzmq not found; installing"
      wget http://download.zeromq.org/${ZEROMQ}.tar.gz
      tar -xf ${ZEROMQ}.tar.gz
      cd ${ZEROMQ}
      ./configure --prefix=$HOME/.stack/local && make && make install
      cd ..
    else
      echo "libzmq found; skipping"
    fi

script:
 - cabal check
 - cabal sdist
 - export SRC=$(cabal info . | awk '{print $2;exit}')
 - tar -xzf "dist/$SRC.tar.gz"
 - cd "$SRC"
 - cp ../$STACK_YAML .
 - cp ../stack .
 - travis_retry ./stack setup
 - travis_retry ./stack install --only-snapshot -j4 --verbosity info
 - ./stack build
 - ./stack haddock --no-haddock-deps
 - ./stack test
